# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cfc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 21, 15, 28, 25, 40857, tzinfo=utc)),
        ),
    ]
