# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cfc', '0002_auto_20170321_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
