# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfc', '0002_auto_20170321_1330'),
        ('cfc', '0003_auto_20170321_1528'),
    ]

    operations = [
    ]
